#!/bin/bash
#
# Exports a mysql database to an sql file using a portable and
# easy to read format.  
#
# The output format will be UTF8 and all tables will be converted
# to UTF8 even if one or more of the tables are in Latin1.
#

# set the path to the mysqldump executable
mysqldump_path=/usr/bin/mysqldump

# make sure utf8 is set in the shell, this is
# relevant later when we use sed
export LANG="en_US.UTF-8"


function print_usage() {
	echo "Usage: $0 [OPTIONS] database"
	echo 
	echo "The following options may be given as the first argument:"
	echo "  -p Password to use when connecting to server. If password is"
	echo "     not given it's solicited on the tty."
	echo "  -r Direct output to a given file."
	echo "  -u User for login if not current user."
	echo "  -v Print info about the various stages."
	echo "  -x Compress the output file with gzip."
	echo 
}

# http://wiki.bash-hackers.org/howto/getopts_tutorial
while getopts ":u:p:r:xv" opt; do
	case $opt in
		u)	
			username=$OPTARG 
			;;
		p)
			password=$OPTARG
			;;
		r) 
			output_file=$OPTARG
			;;
		v)
			verbose=true
			;;
		x)
			compress=true
			;;
		\?)
			echo "Invalid option: -$OPTARG"
			print_usage
			exit 1
			;;
		\:)
			echo "Option -$OPTARG requires an argument."
			print_usage
			exit 1
			;;
	esac
done

if [ "$#" -ne $OPTIND ]; then
	echo "You have to specify a database."
	echo 
	print_usage
	exit 1
fi

database=${!#}

if [ -z "$output_file" ]; then
	output_file=${database}-$(date +%Y-%m-%d).sql
	if [ -n "$compress" ]; then
		output_file=${output_file}.gz
	fi

fi


tmp_file1=$(mktemp tmp_mysql-export.sql.XXXXX)
tmp_file2=$(mktemp tmp_mysql-export.sql.XXXXX)

function cleanup() {
	rm $tmp_file1
	rm -f $tmp_file2
}


###############################################################################
# mysqldump settings
###############################################################################
mysqldump_args=""


# Specify username if given as argument
if [ -n "$username" ]; then
	mysqldump_args="$mysqldump_args -u $username"
fi

# Specify username if given as argument. If not use interactive password. No password not supported.
if [ -n "$password" ]; then
	mysqldump_args="$mysqldump_args -p$password"
else 
	mysqldump_args="$mysqldump_args -p"
fi


# Overrides the default settings and forces the server to send us data in UTF8.
# This will set the environment variables character_set_client, 
# character_set_connection and character_set_results to UTF8. 
mysqldump_args="$mysqldump_args --default-character-set utf8"

# Do not write SET NAMES statement
mysqldump_args="$mysqldump_args --skip-set-charset"

# Dump binary columns using hexadecimal notation. This is useful because if
# anyone tries to change the encoding of the file it will break. 
mysqldump_args="$mysqldump_args --hex-blob"

# Writes every insert as a single line. Normally it would bunch them all
# up in a very very long line, making it hard to read in a text editor.
# Be aware that this will make things a lot slower.
#mysqldump_args="$mysqldump_args --skip-extended-insert"

# Runs the entire dump in a single transation so that anything that changes
# during the time that we dump the database will not be included in the
# dump.
mysqldump_args="$mysqldump_args --single-transaction"

# Forces mysqldump to retrieve rows for a table from the server a row at a 
# time rather than retrieving the entire row set and buffering it in memory 
# before writing it out.
mysqldump_args="$mysqldump_args --quick"

mysqldump_args="$mysqldump_args $database"



###############################################################################
# dump database structure 
###############################################################################
echo "Dumping database..."
cmd="$mysqldump_path -r $tmp_file1 $mysqldump_args" 

if [ -n "$verbose" ]; then
	echo $cmd
fi
$cmd

if [ $? -ne 0 ]; then
	echo "Failed to dump structure. Aborting."
	cleanup
	exit 2
fi

###############################################################################
# replace charset in tables
###############################################################################

# The create table statements in the file may specify a character set. Replace
# any references to latin1

echo "Replacing charset..."
sed "s/DEFAULT CHARACTER SET latin1/DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci/" < $tmp_file1 | sed "s/DEFAULT CHARSET=latin1/DEFAULT CHARSET=utf8/" > $tmp_file2

if [ $? -ne 0 ]; then
   echo "Failed to replace charset. Aborting."
   cleanup
   exit 4
fi


###############################################################################
# Concatenate files
###############################################################################

echo "Writing output to $output_file..."
if [ -z "$compress" ]; then
	mv $tmp_file2 $output_file
else
	cat $tmp_file2 | gzip > $output_file
fi

cleanup
echo "Done."
echo "Remember to use --default-character-set utf8 with mysql when importing!"
echo
